### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by not-my-profile** [tardyp/sphinx-jinja#21]
I'd like to use the `jinja_filters` option introduced in #18 in a project that doesn't have any bleeding edge dependencies.

**Comment by tardyp** [comment]
I just released 1.2.0

**Comment by not-my-profile** [comment]
Thanks for the quick reaction!

I'm afraid you made a small mistake by specifying `Jinja2 = "^2.11.2"` in `pyproject.toml`.

sphinx-jinja 1.1.1 was compatible with the latest Jinja2 3.0.3 ... it doesn't make sense that the new sphinx-jinja version requires an old version of Jinja2.

**Comment by tardyp** [comment]
I just release 1.2.1 to release this tight dependency
