### ISSUE TITLE
ERROR: Unknown directive type "jinja". when building on RTD 

### ISSUE THREAD

**Issue by JSKenyon** [tardyp/sphinx-jinja#29]
I am a relatively new user attempting to get my docs to display on RTD. Unfortunately, I keep running into `ERROR: Unknown directive type "jinja".` This is unusual because I do not see this locally - it only happens on RTD. It is completely plausible that something is wrong with my setup, but I was hoping that someone more experienced than me might know what the problem is. The repo in question is https://github.com/JSKenyon/QuartiCal.

**Comment by JSKenyon** [comment]
I can confirm that sphinx-jinja does seem to be installed during setup though (looking at the RTD logs).

**Comment by tardyp** [comment]
I think you should rather ask on RTD expertise forums. 

I am not sure how you can install sphinx plugins in RTD

**Comment by JSKenyon** [comment]
Thanks, but I think this was just an amateurish user error on my part. Closing for now.
