### ISSUE TITLE
Sphinx 5.0.1 has been released

### ISSUE THREAD

**Issue by return42** [tardyp/sphinx-jinja#35]
Sphinx 5.0.1 has been released, can you update dependencies / thanks!

https://github.com/tardyp/sphinx-jinja/blob/700800cb73bf7a0ad2283e7ec798324c840fb8a4/pyproject.toml#L18

**Comment by return42** [comment]
Hi @tardyp pardon my impatience but the dependencies begin to cascade; more and more upgrades can't be done as long we have sphinx-tabs in our dependencies.

Could you please have a look / thanks a lot!

**Comment by tardyp** [comment]
Sorry, I though that this PR was just a preparation, and wasn't actually working. Looks from the test that it does work.
If you agree with changing the dep to >4.2 I think this will avoid unnecessary dependency constraint

**Comment by return42** [comment]
> If you agree with changing the dep to >4.2 I think this will avoid unnecessary dependency constraint

Yes feel free to modify .. thanks a lot :+1:

**Comment by tardyp** [comment]
I've pushed a new version https://pypi.org/project/sphinx-jinja/2.0.2/ let me know if this works for you..

**Comment by return42** [comment]
@tardyp: works like a charm .. we have several usage of your module, to pick one:

this side: https://docs.searxng.org/admin/engines/configured_engines.html

is rendered from this reST: https://github.com/searxng/searxng/blob/master/docs/admin/engines/configured_engines.rst

Thank you again for providing us with this great module :+1:
